/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosPedidoIdRouteImport } from './routes/pedidos.$pedidoId'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'
import { Route as ApiWebhooksCaktoRouteImport } from './routes/api.webhooks.cakto'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosPedidoIdRoute = PedidosPedidoIdRouteImport.update({
  id: '/$pedidoId',
  path: '/$pedidoId',
  getParentRoute: () => PedidosRoute,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => ClientesRoute,
} as any)
const ApiWebhooksCaktoRoute = ApiWebhooksCaktoRouteImport.update({
  id: '/api/webhooks/cakto',
  path: '/api/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/entregas': typeof EntregasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/pedidos/$pedidoId': typeof PedidosPedidoIdRoute
  '/api/webhooks/cakto': typeof ApiWebhooksCaktoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/entregas': typeof EntregasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/pedidos/$pedidoId': typeof PedidosPedidoIdRoute
  '/api/webhooks/cakto': typeof ApiWebhooksCaktoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/entregas': typeof EntregasRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/pedidos/$pedidoId': typeof PedidosPedidoIdRoute
  '/api/webhooks/cakto': typeof ApiWebhooksCaktoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/assinatura'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/entregas'
    | '/financeiro'
    | '/login'
    | '/nova-senha'
    | '/orcamentos'
    | '/pedidos'
    | '/producao'
    | '/recuperar-senha'
    | '/clientes/$clienteId'
    | '/pedidos/$pedidoId'
    | '/api/webhooks/cakto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/assinatura'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/entregas'
    | '/financeiro'
    | '/login'
    | '/nova-senha'
    | '/orcamentos'
    | '/pedidos'
    | '/producao'
    | '/recuperar-senha'
    | '/clientes/$clienteId'
    | '/pedidos/$pedidoId'
    | '/api/webhooks/cakto'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/assinatura'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/entregas'
    | '/financeiro'
    | '/login'
    | '/nova-senha'
    | '/orcamentos'
    | '/pedidos'
    | '/producao'
    | '/recuperar-senha'
    | '/clientes/$clienteId'
    | '/pedidos/$pedidoId'
    | '/api/webhooks/cakto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AssinaturaRoute: typeof AssinaturaRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EntregasRoute: typeof EntregasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PedidosRoute: typeof PedidosRouteWithChildren
  ProducaoRoute: typeof ProducaoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ApiWebhooksCaktoRoute: typeof ApiWebhooksCaktoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$pedidoId': {
      id: '/pedidos/$pedidoId'
      path: '/$pedidoId'
      fullPath: '/pedidos/$pedidoId'
      preLoaderRoute: typeof PedidosPedidoIdRouteImport
      parentRoute: typeof PedidosRoute
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/api/webhooks/cakto': {
      id: '/api/webhooks/cakto'
      path: '/api/webhooks/cakto'
      fullPath: '/api/webhooks/cakto'
      preLoaderRoute: typeof ApiWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientesRouteChildren {
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteIdRoute: ClientesClienteIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface PedidosRouteChildren {
  PedidosPedidoIdRoute: typeof PedidosPedidoIdRoute
}

const PedidosRouteChildren: PedidosRouteChildren = {
  PedidosPedidoIdRoute: PedidosPedidoIdRoute,
}

const PedidosRouteWithChildren =
  PedidosRoute._addFileChildren(PedidosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AssinaturaRoute: AssinaturaRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EntregasRoute: EntregasRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  OrcamentosRoute: OrcamentosRoute,
  PedidosRoute: PedidosRouteWithChildren,
  ProducaoRoute: ProducaoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ApiWebhooksCaktoRoute: ApiWebhooksCaktoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
